export const ACTIVE_TAB = "ACTIVE_TAB"

export const GET_ERRORS = "GET_ERRORS"
export const CLEAR_ERRORS = "CLEAR_ERRORS"

export const AUTH_LOADING = "AUTH_LOADING"
export const REGISTRATION_SUCCESS = "REGISTRATION_SUCCESS"
export const SET_CURRENT_USER = "SET_CURRENT_USER"
