export { default as Gallery } from "./Gallery/Gallery"
export { default as History } from "./History/History"
export { default as Records } from "./Records/Records"
export { default as Season } from "./Season/Season"
export { default as PlayerList } from "./Players/PlayerList"
export { default as PlayerDetails } from "./Players/PlayerDetails"
